# Generated by Django 4.2.7 on 2023-11-30 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_delete_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="maincomment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="home_page",
        ),
    ]
