# Generated by Django 4.2.7 on 2023-11-30 16:58

import comment.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0003_alter_comment_options_alter_maincomment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                null=True, upload_to=comment.models.comment_image_file_path
            ),
        ),
        migrations.AddField(
            model_name="maincomment",
            name="image",
            field=models.ImageField(
                null=True, upload_to=comment.models.comment_image_file_path
            ),
        ),
    ]
